audit_header: false
title: Pismo Coast Real Estate Video Blog with Sylvia Lunsford
description: Our mission at Outland and Associates is to be your best resource for Central Coast real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Outland and Associates, your professional Pismo Beach Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Sylvia Lunsford
  title: REALTOR®
  license_number: 'DRE# 01232890'
  about_markdown: |
    For over two decades Sylvia Lunsford has passionately served her clients by establishing rapport, building trust, and creating lasting partnerships.  Her extensive background in real estate, finance, and marketing enables her to draw from a deep well of knowledge and life experience to help her clients make informed and intelligent decisions.

    A dynamic Realtor® with in-depth knowledge and a broad range of strengths makes her a standout leader in the Central Coast real estate market.  Described by her peers and clients as caring, insightful and determined, Sylvia goes beyond expectations to serve.  She is inherently attentive to clients’ goals, needs and desires, tirelessly assisting them at every point of the selling and buying process.

    Sylvia gained certification in 2009 as a Distressed Property Expert (CDPE), and also became a Certified Luxury Home Marketing Specialist (CLHMS) in 2010, a designation requiring verified property sales in the top 10% of the market.
  brand: Outland and Associates Real Estate
  brokerage: Central Coast
  market: Central Coast
  address:
  phone: 805-748-5900
  phone_type:
  phone2:
  phone2_type:
  email: sylvia@pismocoastrealestate.com
  url:

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Find Homes in Your Area
  second_CTA_URL: /homesearch/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Central Coast Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Central Coast Home?"
    CTA_text2: "Learn more about available homes in your area."
    CTA_link_text2: "Find Homes in Your Area"
    CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Pismo Beach Real Estate Podcast with Sylvia Lunsford'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Pismo Beach Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Outland and Associates - your professional Pismo Beach Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Pismo Beach, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Sylvia Lunsford'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 20
  hero_text: Pismo Coast Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#65A604'
  theme_color: '#225574'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 2px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#017F7E'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
